### ISSUE TITLE
handlebars-layouts not being processed correctly

### ISSUE THREAD

**Issue by remove-checksum** [partiellkorrekt/parcel-transformer-handlebars#1]
Thanks for a neat plugin!

Sadly, when attempting to use handlebars-layouts syntax it replaces `{{#extend}}` clauses with `[object Object]` string
[Reproduction here](https://github.com/remove-checksum/handlebars-parcel-repro)

[This package](https://github.com/anikinaa/parcel-transformer-handlebars), however, renders layouts just fine? But its also uses older  `handlebars 4.0.11` and dont invalidate parcel assets at all (no hot-reload on file changes)

Maybe problem lays with `handlebars 4.6.0` closing prototype method access

**Comment by partiellkorrekt** [comment]
I have published an update that should fix this issue. Somehow handlebarsHelpers was interfering with handlebarsLayouts. Now the plugin should work for your use-case. Although I think it would be worth investigating what the actual problem was.

Should the plugin not work feel free to add another comment here.
